apiVersion: v1
kind: Pod
metadata: 
  name: go-pod
  labels: 
    app: go-demo
spec: 
  containers: 
  - name: go-container
    image: go-hello
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080